### ISSUE TITLE
Step by step guide

### ISSUE THREAD

**Issue by naazy** [dwyl/automatic-postgres-backups-on-heroku-deployment#1]
After struggling to find an easy solution on Google when setting up these backups up on a project and talking to @mk4111 and @JMurphyWeb who are setting up similar backups atm, I thought it would be a good idea to write up a quick guide

**Comment by mk4111** [comment]
This'd help us biiiiig time!! :+1: :100: :1st_place_medal: :wine_glass: :peace_symbol:  :yin_yang: :monkey:

**Comment by naazy** [comment]
@mk4111 / @JMurphyWeb I've just made a PR https://github.com/dwyl/automatic-postgres-backups-on-heroku-deployment/pull/2 so hopefully this will be ready for you to try out next week! :woman_cartwheeling: Let me know if there's anything that doesn't make sense via the issues 😄
