### ISSUE TITLE
mysql backups

### ISSUE THREAD

**Issue by jay-meister** [dwyl/automatic-postgres-backups-on-heroku-deployment#3]
I have written a script for auto backups of a ClearDB mysql database on Heroku. It should work with a different DB provider too.

Mysql buildpack that needs to run before the nodejs buildpack: https://github.com/Shopify/heroku-buildpack-mysql

```sh
#!/bin/bash

#install aws-cli
curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
unzip awscli-bundle.zip
chmod +x ./awscli-bundle/install
./awscli-bundle/install -i /tmp/aws

# new backup file name
BACKUP_FILE_NAME="$(date +"%Y-%m-%d-%H-%M")-$APP-$DATABASE.sql"


# if directory '/tmp/db-backups' doesn't exist, create it
if [ ! -d "/tmp/db-backups" ]; then
  mkdir -p /tmp/db-backups/
fi

# dump the current DB into /tmp/db-backups/<new-file-name>
./bin/mysqldump -u $CLEARDB_USER_NAME -h $CLEARDB_SERVER_IP -p$CLEARDB_PASSWORD --databases $DATABASE | gzip -c > "/tmp/db-backups/$BACKUP_FILE_NAME.gz"

# using the aws cli, copy the new backup to our s3 bucket
/tmp/aws/bin/aws s3 cp /tmp/db-backups/$BACKUP_FILE_NAME.gz s3://$S3_BUCKET_PATH/$DATABASE/$BACKUP_FILE_NAME.gz --region=$AWS_DEFAULT_REGION

echo "backup $BACKUP_FILE_NAME.gz complete"
```

**Comment by nelsonic** [comment]
Nice one @JMurphyWeb 🥇 
Might be worth re-naming the repo to:
`automatic-database-backups-on-heroku-deployment` ? 
@naazy your decision.

**Comment by naazy** [comment]
Done @nelsonic :)
@JMurphyWeb do you want to write up a wee section on setting up automatic backups with MySQL? ☮️

**Comment by jay-meister** [comment]
@naazy i am working on getting this integrated as we speak. Will PR something soon 🇵🇸

**Comment by jay-meister** [comment]
btw typo in the name?

**Comment by naazy** [comment]
@JMurphyWeb hmm? what's the typo? 😕

**Comment by jay-meister** [comment]
For me it used to say `deploymen`

**Comment by jay-meister** [comment]
@naazy by running a backup in the postinstall part of the deployment lifecycle, does that install a backup of the current DB state, before any changes are made by the new deployment?

**Comment by naazy** [comment]
@JMurphyWeb Yes. My understanding is that the postinstall is run immediately after your install (e.g. npm install). If your migrations run in your postinstall also then it's important to put your backup script first within your postinstall i.e. ```npm run backup; npm run migrations;```

**Comment by jay-meister** [comment]
@nelsonic can i get push rights to this baby?

**Comment by naazy** [comment]
@JMurphyWeb i've made you a collaborator ☮️

**Comment by naazy** [comment]
This is complete and has been merged into master. Thanks @JMurphyWeb 🌈
